version: 2

updates:
  # Main docker
  - package-ecosystem: docker
    directory: "/docker"
    schedule:
      interval: daily
      time: "02:00"
      timezone: "Europe/Bratislava"
    reviewers:
      - matejkosiarcik
    assignees:
      - matejkosiarcik
    open-pull-requests-limit: 1
    labels:
      - automerge

  # Dependencies
  - package-ecosystem: npm
    directory: "/docker/dependencies"
    versioning-strategy: increase
    schedule:
      interval: daily
      time: "01:00"
      timezone: "Europe/Bratislava"
    reviewers:
      - matejkosiarcik
    assignees:
      - matejkosiarcik
    open-pull-requests-limit: 1
    labels:
      - automerge
