version: 2

updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
      time: "00:30"
      timezone: "Europe/Bratislava"
    reviewers:
      - matejkosiarcik
    assignees:
      - matejkosiarcik
    open-pull-requests-limit: 1
    labels:
      - automerge

  # Main docker
  - package-ecosystem: docker
    directory: "/docker"
    schedule:
      interval: daily
      time: "01:00"
      timezone: "Europe/Bratislava"
    reviewers:
      - matejkosiarcik
    assignees:
      - matejkosiarcik
    open-pull-requests-limit: 1
    labels:
      - automerge

  # Dependencies
  - package-ecosystem: npm
    directory: "/docker/dependencies"
    versioning-strategy: increase
    schedule:
      interval: daily
      time: "01:30"
      timezone: "Europe/Bratislava"
    reviewers:
      - matejkosiarcik
    assignees:
      - matejkosiarcik
    open-pull-requests-limit: 1
    labels:
      - automerge

  # Misc
  - package-ecosystem: npm
    directory: "/doc/record"
    versioning-strategy: increase
    schedule:
      interval: daily
      time: "02:00"
      timezone: "Europe/Bratislava"
    reviewers:
      - matejkosiarcik
    assignees:
      - matejkosiarcik
    open-pull-requests-limit: 1
    labels:
      - automerge
  - package-ecosystem: pip
    directory: "/doc/record"
    schedule:
      interval: daily
      time: "02:30"
      timezone: "Europe/Bratislava"
    reviewers:
      - matejkosiarcik
    assignees:
      - matejkosiarcik
    open-pull-requests-limit: 1
    labels:
      - automerge
