version: 2.1

workflows:
  version: 2
  circleci-build:
    jobs:
      - azlint
      - lint
      - build

jobs:
  azlint:
    docker:
      - image: matejkosiarcik/azlint
    steps:
      - checkout
      - run: azlint

  lint:
    docker:
      - image: node:lts
    steps:
      - checkout
      - run: npm ci && npm run lint

  build:
    docker:
      - image: docker
    steps:
      - checkout
      - setup_remote_docker
      - run: apk add --no-cache alpine-sdk nodejs npm bash
      - run: make bootstrap build
